### ISSUE TITLE
Doesn't work on TV - DS Video

### ISSUE THREAD

**Issue by Mikoros** [darknebular/Wrapper_VideoStation#15] opened 2023-04-24 08:03 UTC
Hello,
Thank you very much for the wrapper, it works well on PC and phone app. But unfortunately, I don't know if it's normal, but I still can't read videos with DTS audio on DS Video TV app. In fact, the video plays but without the sound. 
Thanks in advance for your help ^^

**Comment by darknebular** [comment] 2023-04-24 09:12
Hello, could you send me this?

`tail -n 150 -f /tmp/wrapper_ffmpeg.log`

Then copy and paste here the result.

**The applications of the "MarketStore" of the TVs are not updated.** Companies do not maintain them well in their repositories.
For example, Samsung and LG have super old versions of DS-Video and they never uploaded a new version of DS-Video again.

I recommend that you buy a Google-TV and use the DS-Video of this or cast the DS-Video from a mobile to the Google-TV (Chromecast Gen.5).

I would also like to ask if you changed the order of the audio codecs in the Wrapper using the Configurator Tool?

Older DS-Video versions of TVs only support 1 audio stream and not 2. Perhaps if you force the Wrapper to use 2.0 MP3 (it will give you fewer compatibility issues with older DS-Video versions) and force it to use only 1 audio stream, maybe you can make it work with the older DS-Video of the TVs.

**Comment by Mikoros** [comment] 2023-04-24 17:23
> Hello, could you send me this?
> 
> `tail -n 150 -f /tmp/wrapper_ffmpeg.log`
> 
> Then copy and paste here the result.
> 
> **The applications of the "MarketStore" of the TVs are not updated.** Companies do not maintain them well in their repositories. For example, Samsung and LG have super old versions of DS-Video and they never uploaded a new version of DS-Video again.
> 
> I recommend that you buy a Google-TV and use the DS-Video of this or cast the DS-Video from a mobile to the Google-TV (Chromecast Gen.5).
> 
> I would also like to ask if you changed the order of the audio codecs in the Wrapper using the Configurator Tool?
> 
> Older DS-Video versions of TVs only support 1 audio stream and not 2. Perhaps if you force the Wrapper to use 2.0 MP3 (it will give you fewer compatibility issues with older DS-Video versions) and force it to use only 1 audio stream, maybe you can make it work with the older DS-Video of the TVs.

**Thank you for your quick response, so if I understand, i must uninstall the wrapper and reinstall it using options a and g ? 
About the command, here is the result :**

`[2023-04-23 17:30:42] INFO: ==================== Configuration of the Language in this Installer ====================`
`[2023-04-23 17:30:45] INFO: ==================== Changed the Language in this Installer to: FRENCH ====================`
`[2023-04-23 17:31:37] INFO: ==================== Installation of the Simplest Wrapper: START ====================`
`[2023-04-23 17:31:37] INFO: Backup the original ffmpeg41 as ffmpeg41.orig.`
`[2023-04-23 17:31:37] INFO: Injection of the ffmpeg41 wrapper using this injector: simplest.`
`[2023-04-23 17:31:40] INFO: Fixing permissions of the ffmpeg41 wrapper.`
`[2023-04-23 17:31:40] INFO: Adding of the KEY of this Wrapper in /tmp.`
`[2023-04-23 17:31:40] INFO: Backup the original libsynovte.so in VideoStation as libsynovte.so.orig.`
`[2023-04-23 17:31:40] INFO: Fixing permissions of /var/packages/VideoStation/target/lib/libsynovte.so.orig`
`[2023-04-23 17:31:40] INFO: Patching /var/packages/VideoStation/target/lib/libsynovte.so for compatibility with DTS, EAC3 and TrueHD`
`[2023-04-23 17:31:40] INFO: Restarting CodecPack...`
`[2023-04-23 17:31:45] INFO: Restarting VideoStation...`
`[2023-04-23 17:31:52] INFO: ==================== Installation of the Simplest Wrapper: COMPLETE ====================`

`[2023-04-23 17:32:34] [INFO] ========================================[start ffmpeg 12292]`
`[2023-04-23 17:32:34] [INFO] DEFAULT_ARGS: -ss 0.000 -i /volume1/USER NAME/Vidéos, Télévision/Films/Babysitting 1.mkv -threads 0 -vcodec copy -vsync 2 -vbsf h264_mp4toannexb=repeatheader -acodec libmp3lame -ab 256k -ac 2 -f ssegment -segment_format mpegts -segment_list_type m3u8 -hls_seek_time 0 -segment_time 8 -segment_time_delta 0.000 -segment_start_number 00000 -avoid_negative_ts 0 -break_non_keyframes 0 -max_muxing_queue_size 1024 -map 0:0 -map 0:1 /tmp/VideoStation/HLS/3567c24e47ad2c0aa0b8b84ce45358ed_QvhHCAUc/slice-%05d.ts`

`[2023-04-23 17:32:48] [INFO] ========================================[start ffmpeg 12402]`
`[2023-04-23 17:32:48] [INFO] DEFAULT_ARGS: -ss 179.179 -i /volume1/USER NAME/Vidéos, Télévision/Films/Babysitting 1.mkv -threads 0 -vcodec copy -vsync 2 -vbsf h264_mp4toannexb=repeatheader -acodec libmp3lame -ab 256k -ac 2 -f ssegment -segment_format mpegts -segment_list_type m3u8 -hls_seek_time 179179 -segment_time 8 -segment_time_delta 3.179 -segment_start_number 00022 -avoid_negative_ts 0 -break_non_keyframes 0 -max_muxing_queue_size 1024 -map 0:0 -map 0:1 /tmp/VideoStation/HLS/3567c24e47ad2c0aa0b8b84ce45358ed_QvhHCAUc/slice-%05d.ts`
`[2023-04-23 17:33:27] [INFO] ========================================[end ffmpeg 12402]`

`[2023-04-23 17:33:27] [INFO] ========================================[end ffmpeg 12292]`


`[2023-04-23 17:55:22] [INFO] ========================================[start ffmpeg 20790]
[2023-04-23 17:55:22] [INFO] DEFAULT_ARGS: -ss 0.000 -vaapi_device /dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i /volume1/USER NAME/Vidéos, Télévision/Films/Babysitting 1.mkv -vcodec h264_vaapi -vf format=nv12|vaapi,hwupload,scale_vaapi=w=1280:h=688,scale_vaapi=format=nv12 -vsync 2 -bf 0 -vb 1000000 -acodec libmp3lame -ab 128K -ac 2 -f ssegment -segment_format mpegts -segment_list_type m3u8 -hls_seek_time 0 -segment_time 5 -segment_time_delta 0.000 -segment_start_number 00000 -individual_header_trailer 0 -avoid_negative_ts 0 -break_non_keyframes 1 -max_muxing_queue_size 1024 -map 0:0 -map 0:1 /tmp/VideoStation/HLS/3567c24e47ad2c0aa0b8b84ce45358ed_61rhXK9V/slice-%05d.ts`
`[2023-04-23 18:08:55] [INFO] ========================================[end ffmpeg 20790]`


`[2023-04-24 18:07:32] [INFO] ========================================[start ffmpeg 24666]`
`[2023-04-24 18:07:32] [INFO] DEFAULT_ARGS: -ss 0.000 -vaapi_device /dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i /volume1/USER NAME/Vidéos, Télévision/Films/Babysitting 1.mkv -vcodec h264_vaapi -vf format=nv12|vaapi,hwupload,scale_vaapi=w=848:h=448,scale_vaapi=format=nv12 -vsync 2 -bf 0 -vb 500000 -acodec libmp3lame -ab 96k -ac 2 -f ssegment -segment_format mpegts -segment_list_type m3u8 -hls_seek_time 0 -segment_time 5 -segment_time_delta 0.000 -segment_start_number 00000 -individual_header_trailer 0 -avoid_negative_ts 0 -break_non_keyframes 1 -max_muxing_queue_size 1024 -map 0:0 -map 0:1 /tmp/VideoStation/HLS/3567c24e47ad2c0aa0b8b84ce45358ed_prbJvMqI/slice-%05d.ts`
`[2023-04-24 18:20:47] [INFO] ========================================[end ffmpeg 24666]`

**Comment by dsfans** [comment] 2023-04-25 06:52
You have installed the Alex Presso's  Wrapper.
Please, uninstall the other wrapper and then try to re-install again the mine.

You must to install the Advanced One in orden to change the config. With the simplest One you Will can not to change the códecs.

I think that your problem is with the DSVideo's version of your TV.

Regards.

**Comment by darknebular** [comment] 2023-04-25 11:36
Hi, 
NO, He has the MINE, THE SIMPLEST ONE, not the Alex Presso's one.

It's correct, you only can change the order of the audio's codecs using the advance Wrapper.

@Mikoros please re-install the advanced one and then config it using the "Configurator Tool Menu".

Best regards.

**Comment by Mikoros** [comment] 2023-04-25 18:27
Hi,
Unfortunately, I tried but it still doesn't work. I couldn't type "a" and "g" simultaneously so I typed "a" and then did it again with "g" but the result is the same on TV : the video plays without sound.

**Comment by darknebular** [comment] 2023-04-26 07:11
Please, go to VideoStation --> Configuration and confirm me that you have this option enabled: (yellow marked)
![image](https://user-images.githubusercontent.com/82757922/234497607-ba04bfd6-7102-409a-97c8-3a8c903b4360.png)

**Comment by darknebular** [comment] 2023-04-26 08:47
> Hello, could you send me this?
> 
> `tail -n 150 -f /tmp/wrapper_ffmpeg.log`
> 
> Then copy and paste here the result.
**Plase now with the advanced, could you send me this?**

`tail -n 150 -f /tmp/wrapper_ffmpeg.log`

Then copy and paste here the result again.

Regards.

**Comment by darknebular** [comment] 2023-04-26 08:51
@misterravlik It depends in your synology model. There are few that doesn´t support hardware transcoding. Could you send me a screenshot of Config-->Advanced in VideoStation?

Regards.

**Comment by misterravlik** [comment] 2023-04-26 08:57
> @misterravlik It depends in your synology model. There are few that doesn´t support hardware transcoding. Could you send me a screenshot of Config-->Advanced in VideoStation?
> 
> Regards.

Thank you. I apparently have an old model and it does not support, DS1513

**Comment by darknebular** [comment] 2023-04-26 08:59
> > @misterravlik It depends in your synology model. There are few that doesn´t support hardware transcoding. Could you send me a screenshot of Config-->Advanced in VideoStation?
> > Regards.
> 
> Thank you. I apparently have an old model and it does not support, DS1513

Yeah, this model has only software transcoding. In newer models, you must have this option.

**Comment by darknebular** [comment] 2023-04-26 09:00
**Remember that the DS-Video versions used on TVs are not maintained and are very old versions. Your problems may be caused by your TV using an old version of DS-Video...**

Best regards.

**Comment by Mikoros** [comment] 2023-04-29 16:19
> Please, go to VideoStation --> Configuration and confirm me that you have this option enabled: (yellow marked) ![image](https://user-images.githubusercontent.com/82757922/234497607-ba04bfd6-7102-409a-97c8-3a8c903b4360.png)

Well, in fact this window doesn't exists on the TV app. I think that unfortunately, the problem really comes from the TV app... Because everything works fine on my computer / phone.

**Comment by darknebular** [comment] 2023-04-30 13:08
Yeah, I think so.

I uninstalled the DS-Video app in my TVs and I am using a Google TV (Chromecast gen. 5.0) or via DLNA using Media Server.

I will close this ticket, I think that the Wrapper is working fine and your problem really comes from the TV app, It's very old.


Best regards.

**Closed by darknebular** 2023-04-30 13:08 UTC
